# See https://cloud.google.com/appengine/docs/standard/php/config/appref for a
# complete list of `app.yaml` directives.

runtime: php74

env_variables:
    GOOGLE_STORAGE_BUCKET: ""
    # populate these to use the "mysql" or "postres" backends
    CLOUDSQL_CONNECTION_NAME: "cloud-formative-2-project:europe-west2:comment-section"
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "password123"
    ## Uncomment to give your database a name other than "bookshelf"
    CLOUDSQL_DATABASE_NAME: "comments"
